"""
Null Control Test 2: Distributional Null Model

Tests whether φ-convergence patterns can emerge from independent sampling
of marginal distributions alone. If synthetic data (generated by sampling
sr1, sr3, sr5 independently from fitted distributions) shows similar
φ-convergence to observed SIE events, then the ratios are NOT special -
they're just statistical artifacts.

Expected φ values (Golden Ratio):
- φ₃₁ (SR3/SR1) = φ² = 2.618033988749895
- φ₅₃ (SR5/SR3) = φ = 1.618033988749895
- φ₅₁ (SR5/SR1) = φ³ = 4.236067977499790
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Force non-interactive backend for file saving
import matplotlib.pyplot as plt
from scipy import stats
from datetime import datetime
import os

# Golden ratio constants
PHI = 1.618033988749895
PHI_SQ = PHI ** 2      # φ² = 2.618033988749895
PHI_CUBED = PHI ** 3   # φ³ = 4.236067977499790

# Configuration
DATA_FILE = 'data/SIE.csv'
N_SYNTHETIC = 10000
OUTPUT_DIR = 'test_output'
FIGURE_FILE = os.path.join(OUTPUT_DIR, 'null_control_2_distributional.png')
REPORT_FILE = os.path.join(OUTPUT_DIR, 'null_control_2_distributional.md')

def load_sie_data(filepath):
    """Load SIE events data"""
    df = pd.read_csv(filepath)
    print(f"Loaded {len(df)} SIE events from {filepath}")
    print(f"Columns: {df.columns.tolist()}")
    return df

def fit_distributions(data):
    """Fit normal distributions to sr1, sr3, sr5"""
    sr1_params = stats.norm.fit(data['sr1'])
    sr3_params = stats.norm.fit(data['sr3'])
    sr5_params = stats.norm.fit(data['sr5'])

    print(f"\nFitted distributions:")
    print(f"  SR1: μ={sr1_params[0]:.4f}, σ={sr1_params[1]:.4f}")
    print(f"  SR3: μ={sr3_params[0]:.4f}, σ={sr3_params[1]:.4f}")
    print(f"  SR5: μ={sr5_params[0]:.4f}, σ={sr5_params[1]:.4f}")

    return sr1_params, sr3_params, sr5_params

def generate_synthetic_samples(sr1_params, sr3_params, sr5_params, n_samples):
    """Generate synthetic samples by INDEPENDENT sampling from fitted distributions"""
    print(f"\nGenerating {n_samples} synthetic samples via independent sampling...")

    synthetic_sr1 = stats.norm.rvs(*sr1_params, size=n_samples, random_state=42)
    synthetic_sr3 = stats.norm.rvs(*sr3_params, size=n_samples, random_state=43)
    synthetic_sr5 = stats.norm.rvs(*sr5_params, size=n_samples, random_state=44)

    return synthetic_sr1, synthetic_sr3, synthetic_sr5

def calculate_phi_errors(sr1, sr3, sr5):
    """Calculate φ-convergence errors for given frequency values"""
    # Calculate ratios
    ratio_31 = sr3 / sr1  # SR3/SR1
    ratio_53 = sr5 / sr3  # SR5/SR3
    ratio_51 = sr5 / sr1  # SR5/SR1

    # Calculate percent errors from golden ratio expectations
    error_31 = np.abs(ratio_31 - PHI_SQ) / PHI_SQ * 100
    error_53 = np.abs(ratio_53 - PHI) / PHI * 100
    error_51 = np.abs(ratio_51 - PHI_CUBED) / PHI_CUBED * 100

    # Composite error (mean of three ratio errors)
    composite_error = (error_31 + error_53 + error_51) / 3

    return {
        'ratio_31': ratio_31,
        'ratio_53': ratio_53,
        'ratio_51': ratio_51,
        'error_31': error_31,
        'error_53': error_53,
        'error_51': error_51,
        'composite': composite_error
    }

def statistical_comparison(obs_errors, synth_errors):
    """Compare observed vs synthetic error distributions"""
    # Mann-Whitney U test
    u_stat, p_value = stats.mannwhitneyu(obs_errors, synth_errors, alternative='less')

    # Effect size (Cohen's d)
    mean_diff = np.mean(obs_errors) - np.mean(synth_errors)
    pooled_std = np.sqrt((np.var(obs_errors) + np.var(synth_errors)) / 2)
    cohens_d = mean_diff / pooled_std

    return {
        'u_stat': u_stat,
        'p_value': p_value,
        'cohens_d': cohens_d,
        'obs_mean': np.mean(obs_errors),
        'obs_std': np.std(obs_errors),
        'synth_mean': np.mean(synth_errors),
        'synth_std': np.std(synth_errors)
    }

def create_visualization(obs_results, synth_results, stats_results):
    """Create 4-panel visualization"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('Null Control 5: Distributional Null Model\nφ-Convergence in Observed vs Synthetic Data',
                 fontsize=14, fontweight='bold')

    # Panel A: Composite Error Distributions
    ax = axes[0, 0]
    ax.hist(obs_results['composite'], bins=50, alpha=0.6, label='Observed SIE', color='blue', density=True)
    ax.hist(synth_results['composite'], bins=50, alpha=0.6, label='Synthetic (Independent)', color='red', density=True)
    ax.axvline(np.mean(obs_results['composite']), color='blue', linestyle='--', linewidth=2, label=f'Obs Mean={np.mean(obs_results["composite"]):.2f}%')
    ax.axvline(np.mean(synth_results['composite']), color='red', linestyle='--', linewidth=2, label=f'Synth Mean={np.mean(synth_results["composite"]):.2f}%')
    ax.set_xlabel('Composite φ-Error (%)', fontsize=11)
    ax.set_ylabel('Density', fontsize=11)
    ax.set_title('A: Composite Error Distribution', fontsize=12, fontweight='bold')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    # Panel B: Individual Ratio Errors (Bar Chart)
    ax = axes[0, 1]
    ratio_names = ['φ₃₁\n(SR3/SR1)', 'φ₅₃\n(SR5/SR3)', 'φ₅₁\n(SR5/SR1)']
    obs_means = [np.mean(obs_results['error_31']), np.mean(obs_results['error_53']), np.mean(obs_results['error_51'])]
    synth_means = [np.mean(synth_results['error_31']), np.mean(synth_results['error_53']), np.mean(synth_results['error_51'])]

    x = np.arange(len(ratio_names))
    width = 0.35
    ax.bar(x - width/2, obs_means, width, label='Observed SIE', color='blue', alpha=0.7)
    ax.bar(x + width/2, synth_means, width, label='Synthetic', color='red', alpha=0.7)
    ax.set_xlabel('Ratio', fontsize=11)
    ax.set_ylabel('Mean φ-Error (%)', fontsize=11)
    ax.set_title('B: Individual Ratio Errors', fontsize=12, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(ratio_names)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3, axis='y')

    # Panel C: Q-Q Plot
    ax = axes[1, 0]
    stats.probplot(obs_results['composite'], dist="norm", plot=ax)
    ax.set_title('C: Q-Q Plot (Observed Composite Error)', fontsize=12, fontweight='bold')
    ax.set_xlabel('Theoretical Quantiles', fontsize=11)
    ax.set_ylabel('Sample Quantiles', fontsize=11)
    ax.grid(True, alpha=0.3)

    # Panel D: Cumulative Distribution Functions
    ax = axes[1, 1]
    obs_sorted = np.sort(obs_results['composite'])
    synth_sorted = np.sort(synth_results['composite'])
    obs_cdf = np.arange(1, len(obs_sorted) + 1) / len(obs_sorted)
    synth_cdf = np.arange(1, len(synth_sorted) + 1) / len(synth_sorted)

    ax.plot(obs_sorted, obs_cdf, label='Observed SIE', color='blue', linewidth=2)
    ax.plot(synth_sorted, synth_cdf, label='Synthetic', color='red', linewidth=2)
    ax.set_xlabel('Composite φ-Error (%)', fontsize=11)
    ax.set_ylabel('Cumulative Probability', fontsize=11)
    ax.set_title('D: CDF Comparison', fontsize=12, fontweight='bold')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    # Add statistical summary text
    stats_text = (
        f"Mann-Whitney U: p={stats_results['p_value']:.4e}\n"
        f"Cohen's d: {stats_results['cohens_d']:.3f}\n"
        f"Obs: μ={stats_results['obs_mean']:.2f}%, σ={stats_results['obs_std']:.2f}%\n"
        f"Synth: μ={stats_results['synth_mean']:.2f}%, σ={stats_results['synth_std']:.2f}%"
    )
    fig.text(0.99, 0.01, stats_text, fontsize=9, ha='right', va='bottom',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.tight_layout(rect=[0, 0.03, 1, 0.96])
    return fig

def generate_report(obs_results, synth_results, stats_results, n_obs, n_synth):
    """Generate markdown report"""
    report = f"""# Null Control 5: Distributional Null Model

**Test Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Overview

This test evaluates whether φ-convergence patterns can emerge purely from the marginal distributions of SR1, SR3, and SR5 frequencies, without any special coupling between harmonics.

**Hypothesis:** If synthetic data (generated by independently sampling from fitted distributions) shows similar φ-convergence to observed SIE events, then the ratios are NOT special - they're merely statistical artifacts of the frequency distributions.

## Expected φ Values (Golden Ratio)

- **φ₃₁ (SR3/SR1)** = φ² = {PHI_SQ:.15f}
- **φ₅₃ (SR5/SR3)** = φ = {PHI:.15f}
- **φ₅₁ (SR5/SR1)** = φ³ = {PHI_CUBED:.15f}

## Data Summary

- **Observed SIE Events:** {n_obs:,}
- **Synthetic Samples:** {n_synth:,}

## Results

### Composite φ-Error

| Metric | Observed SIE | Synthetic | Difference |
|--------|--------------|-----------|------------|
| Mean (%) | {stats_results['obs_mean']:.3f} | {stats_results['synth_mean']:.3f} | {stats_results['obs_mean'] - stats_results['synth_mean']:.3f} |
| Std Dev (%) | {stats_results['obs_std']:.3f} | {stats_results['synth_std']:.3f} | {stats_results['obs_std'] - stats_results['synth_std']:.3f} |

### Individual Ratio Errors

| Ratio | Expected Value | Observed Mean Error (%) | Synthetic Mean Error (%) |
|-------|----------------|-------------------------|--------------------------|
| φ₃₁ (SR3/SR1) | {PHI_SQ:.6f} | {np.mean(obs_results['error_31']):.3f} | {np.mean(synth_results['error_31']):.3f} |
| φ₅₃ (SR5/SR3) | {PHI:.6f} | {np.mean(obs_results['error_53']):.3f} | {np.mean(synth_results['error_53']):.3f} |
| φ₅₁ (SR5/SR1) | {PHI_CUBED:.6f} | {np.mean(obs_results['error_51']):.3f} | {np.mean(synth_results['error_51']):.3f} |

### Statistical Comparison

- **Mann-Whitney U Test:** U = {stats_results['u_stat']:.2f}, p = {stats_results['p_value']:.4e}
- **Effect Size (Cohen's d):** {stats_results['cohens_d']:.3f}

## Interpretation

"""

    # Interpretation based on results
    if stats_results['p_value'] < 0.001:
        if stats_results['cohens_d'] < -0.5:  # Observed better than synthetic
            verdict = "**PASS** ✓"
            interpretation = f"""The observed SIE events show **significantly better φ-convergence** than synthetic data generated from independent distributions (p < 0.001, Cohen's d = {stats_results['cohens_d']:.3f}).

This indicates that the φ-ratios are **NOT merely distributional artifacts**. The observed harmonic coupling appears to represent genuine coordination that cannot be explained by marginal frequency distributions alone.

**Conclusion:** The φ-convergence in SIE events is a real phenomenon, not a statistical artifact of independent frequency sampling."""
        else:
            verdict = "**FAIL** ✗"
            interpretation = f"""The observed SIE events show **similar or worse φ-convergence** compared to synthetic data (p < 0.001, but Cohen's d = {stats_results['cohens_d']:.3f}).

This suggests that the φ-ratios MAY be distributional artifacts that emerge naturally from independent sampling of frequency distributions.

**Conclusion:** The φ-convergence claims require further investigation. The patterns may not be as special as claimed."""
    elif stats_results['p_value'] < 0.05:
        verdict = "**MARGINAL**"
        interpretation = f"""The observed SIE events show statistically significant but modest differences from synthetic data (p = {stats_results['p_value']:.4f}, Cohen's d = {stats_results['cohens_d']:.3f}).

The evidence is suggestive but not conclusive. Further investigation needed.

**Conclusion:** Results are inconclusive regarding whether φ-convergence is a real phenomenon or distributional artifact."""
    else:
        verdict = "**FAIL** ✗"
        interpretation = f"""No significant difference between observed and synthetic φ-convergence (p = {stats_results['p_value']:.4f}).

The φ-ratios appear to be **distributional artifacts** that emerge naturally from independent frequency sampling.

**Conclusion:** The observed φ-convergence is likely NOT a special phenomenon - it's just math emerging from marginal distributions."""

    report += f"{verdict}\n\n{interpretation}\n"

    report += f"""
## Visualization

![Distributional Null Model Results]({os.path.basename(FIGURE_FILE)})

## Technical Notes

1. **Distribution Fitting:** Normal distributions fitted to observed SR1, SR3, SR5 using maximum likelihood
2. **Independent Sampling:** Synthetic samples generated by separately sampling from each fitted distribution (breaking any real coupling)
3. **Sample Size:** {n_synth:,} synthetic samples for robust comparison
4. **Statistical Test:** Mann-Whitney U (non-parametric, no normality assumption)
5. **Effect Size:** Cohen's d for practical significance assessment

---
*Generated by null_control_2_distributional.py*
"""

    return report

def main():
    """Main execution"""
    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("=" * 70)
    print("NULL CONTROL 5: DISTRIBUTIONAL NULL MODEL")
    print("=" * 70)

    # Load data
    data = load_sie_data(DATA_FILE)
    n_obs = len(data)

    # Check if pre-computed ratios exist in CSV
    has_precomputed = all(col in data.columns for col in ['sr3/sr1', 'sr5/sr1', 'sr5/sr3'])

    if has_precomputed:
        print("\nUsing pre-computed ratio columns from CSV (actual detected harmonics)")
        # Use pre-computed ratios directly
        obs_ratio_31 = data['sr3/sr1'].values
        obs_ratio_51 = data['sr5/sr1'].values
        obs_ratio_53 = data['sr5/sr3'].values

        # Calculate errors directly from ratios
        obs_error_31 = np.abs(obs_ratio_31 - PHI_SQ) / PHI_SQ * 100
        obs_error_53 = np.abs(obs_ratio_53 - PHI) / PHI * 100
        obs_error_51 = np.abs(obs_ratio_51 - PHI_CUBED) / PHI_CUBED * 100
        obs_composite = (obs_error_31 + obs_error_53 + obs_error_51) / 3

        obs_results = {
            'ratio_31': obs_ratio_31,
            'ratio_53': obs_ratio_53,
            'ratio_51': obs_ratio_51,
            'error_31': obs_error_31,
            'error_53': obs_error_53,
            'error_51': obs_error_51,
            'composite': obs_composite
        }

        print(f"  Mean errors from pre-computed ratios:")
        print(f"    φ₃₁: {np.mean(obs_error_31):.3f}%")
        print(f"    φ₅₃: {np.mean(obs_error_53):.3f}%")
        print(f"    φ₅₁: {np.mean(obs_error_51):.3f}%")
        print(f"    Composite: {np.mean(obs_composite):.3f}%")
    else:
        print("\nNo pre-computed ratios found, calculating from sr1, sr3, sr5")

    # Fit distributions to individual frequencies
    sr1_params, sr3_params, sr5_params = fit_distributions(data)

    # Generate synthetic samples
    synth_sr1, synth_sr3, synth_sr5 = generate_synthetic_samples(
        sr1_params, sr3_params, sr5_params, N_SYNTHETIC
    )

    # Calculate φ-errors for observed data (if not already done)
    if not has_precomputed:
        print("\nCalculating φ-errors for observed data...")
        obs_results = calculate_phi_errors(
            data['sr1'].values,
            data['sr3'].values,
            data['sr5'].values
        )

    # Calculate φ-errors for synthetic data
    print("\nCalculating φ-errors for synthetic data...")
    synth_results = calculate_phi_errors(synth_sr1, synth_sr3, synth_sr5)

    # Statistical comparison
    print("\nPerforming statistical comparison...")
    stats_results = statistical_comparison(
        obs_results['composite'],
        synth_results['composite']
    )

    # Print results
    print("\n" + "=" * 70)
    print("RESULTS")
    print("=" * 70)
    print(f"\nComposite φ-Error:")
    print(f"  Observed:  μ = {stats_results['obs_mean']:.3f}%, σ = {stats_results['obs_std']:.3f}%")
    print(f"  Synthetic: μ = {stats_results['synth_mean']:.3f}%, σ = {stats_results['synth_std']:.3f}%")
    print(f"\nStatistical Test:")
    print(f"  Mann-Whitney U: {stats_results['u_stat']:.2f}")
    print(f"  p-value: {stats_results['p_value']:.4e}")
    print(f"  Cohen's d: {stats_results['cohens_d']:.3f}")

    # Interpretation
    if stats_results['p_value'] < 0.001 and stats_results['cohens_d'] < -0.5:
        print(f"\n✓ PASS: Observed φ-convergence is significantly better than synthetic")
        print(f"  → φ-ratios are NOT distributional artifacts")
    else:
        print(f"\n✗ FAIL/INCONCLUSIVE: Observed and synthetic show similar φ-convergence")
        print(f"  → φ-ratios may be distributional artifacts")

    # Create visualization
    print(f"\nGenerating visualization...")
    fig = create_visualization(obs_results, synth_results, stats_results)
    fig.savefig(FIGURE_FILE, dpi=300, bbox_inches='tight')
    print(f"Saved: {FIGURE_FILE}")
    plt.close(fig)

    # Generate report
    print(f"Generating report...")
    report = generate_report(obs_results, synth_results, stats_results, n_obs, N_SYNTHETIC)
    with open(REPORT_FILE, 'w') as f:
        f.write(report)
    print(f"Saved: {REPORT_FILE}")

    print("\n" + "=" * 70)
    print("ANALYSIS COMPLETE")
    print("=" * 70)

if __name__ == '__main__':
    main()
